events {
    worker_connections 1024;
}

http {
    upstream pivot_functions {
        server pivot-functions:8080;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://pivot_functions;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

