// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVINq4q-n6WxDMQugnktHYg_r_zwRKD7w',
    appId: '1:961104767168:web:3494534af9801736cb2525',
    messagingSenderId: '961104767168',
    projectId: 'pivot-28563',
    authDomain: 'pivot-28563.firebaseapp.com',
    storageBucket: 'pivot-28563.firebasestorage.app',
    measurementId: 'G-MTDPKDS6WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_tQ2J1rzHQs4YlM4sn-koH87mVadzq7I',
    appId: '1:961104767168:android:5040d3662ce98228cb2525',
    messagingSenderId: '961104767168',
    projectId: 'pivot-28563',
    storageBucket: 'pivot-28563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6vR7WlqcPLZm0ph42P1-OReiI7A5PL4k',
    appId: '1:961104767168:ios:a8e3e77e16fbe691cb2525',
    messagingSenderId: '961104767168',
    projectId: 'pivot-28563',
    storageBucket: 'pivot-28563.firebasestorage.app',
    iosBundleId: 'com.example.pivot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6vR7WlqcPLZm0ph42P1-OReiI7A5PL4k',
    appId: '1:961104767168:ios:a8e3e77e16fbe691cb2525',
    messagingSenderId: '961104767168',
    projectId: 'pivot-28563',
    storageBucket: 'pivot-28563.firebasestorage.app',
    iosBundleId: 'com.example.pivot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVINq4q-n6WxDMQugnktHYg_r_zwRKD7w',
    appId: '1:961104767168:web:61fa7c7aba64cd09cb2525',
    messagingSenderId: '961104767168',
    projectId: 'pivot-28563',
    authDomain: 'pivot-28563.firebaseapp.com',
    storageBucket: 'pivot-28563.firebasestorage.app',
    measurementId: 'G-1M0EMYV7XC',
  );
}
